### ISSUE TITLE
Somethink like Amnesia

### ISSUE THREAD

**Issue by SuperWes** [IGDAStl/gateway2dwest#1]
We should do a game like Amnesia

**Comment by terrortimmy** [comment]
a text-based game?  this Amnesia?  https://en.wikipedia.org/wiki/Amnesia_%28video_game%29
or survival-horror game? like Amnesia: The Dark Descent?  https://en.wikipedia.org/wiki/Amnesia:_The_Dark_Descent

**Comment by zfalconer** [comment]
always wanted to do a text-based game!

**Comment by SuperWes** [comment]
I think the person who suggested this was pushing for something like Amnesia: The Dark Descent

**Comment by SuperWes** [comment]
This is an excellent idea, but the group has spoken and we will be making a Spelunky-style random dungeons as a top down action adventure (Gauntlet/Binding of Isaac)
