### ISSUE TITLE
Multiple Pull Requests?

### ISSUE THREAD

**Issue by CaliberMengsk** [IGDAStl/gateway2dwest#11]
So, earlier in the night, I did a pull request to add tilemaster, figuring I wouldn't do anything else tonight, but then... I did more stuff. In this case, should I just do another pull request without canceling the original one, or should I cancel the original and just do another pull request?

I really don't get git much, so sorry for the confusion.

EDIT:
At the moment, I'm simply going to hold off on the new stuff. It's just some extra comments and a little bit of changes to the player movement, and adding an extension for cameras in orthographic view (bounds and extents), so nothing immediately important, I just figured we should know what to do in this situation. I guess best practice would be just don't do a pull request until you are certain you are done... but I'm too impatient :P.

**Comment by SuperWes** [comment]
To be honest, I'm learning it at the same time. I think the best practice
is to create a branch that represents the feature (add tilemaster), do a
pull request for that, then create another branch that represents the extra
work and do a pull request for that. This helps the project owner make sure
that they know what they're looking for when they pull the code in.

Thanks for your help man!

-Wes

**Comment by Tolk-Haggard** [comment]
The way github works, if you do a pull request and then add additional commits to your branch you are pulling from, they are automatically added to a pull request. I think the reason it works that way, is pull requests are a place where dialogue can occur about the pull request. As changes are suggested, commits can be changed or added. If it required a new pull request to pick up changes all the dialogue would be lost with each change.

So if you want to have 2 separate pull requests going with different content, you will need 2 branches.

**Comment by CaliberMengsk** [comment]
Seems either like you said, it automatically put everything else I did into the pull, or doing a second pull request automatically adds everything into the first. Either way, all updates are there, so :D
