### ISSUE TITLE
Hipchat may be a good idea...

### ISSUE THREAD

**Issue by CaliberMengsk** [IGDAStl/gateway2dwest#5]
So, Hipchat is a pretty spiffy chat system that lets you integrate a lot of development tools into it. So for instance, we can add this repository to it's github plugin, and when people do commits, pull requests, etc, it sends a chat message to everyone in the chat. It can also be integrated in Trello.

I already have an account from a past venture with a few people, so I set up a publicly available room with guest access, so anyone can join. Ignore the whole "Mecha" thing. I don't know how to change that...

Anyway, Link for those that want to try it out.
https://www.hipchat.com/gUNi66HSC

I do need to be a priveleged user to actually add the repo though as it authenticates through github api's... or I can just add Wes as a priveleged user on hipchat. Anyway, that's all for now.

--Randy

**Comment by SuperWes** [comment]
I was thinking the same thing.

**Comment by cassdeckard** [comment]
We could also use Slack I think. How likely is it that we would run into their 10,000 message limitation on the free version?

**Comment by CaliberMengsk** [comment]
Just checked, and hipchat is 25,000 messages logged per room, not that it matters a ton as far as a log. Just a few hundred messages is fine with me, though it could be useful I suppose.

**Comment by alphathreethree** [comment]
Hipchat seems pretty cool, but I think we may be better served with a system like a message board. Every time I have been in the hipchat room no one has been there (obviously). The live chat only works when we are all on the same schedule or all working at the same time. (unless I am just not understanding how to use hipchat)

**Comment by CaliberMengsk** [comment]
Hipchat keeps a record of the last 25,000 messages, so even if no one is there, when the next person comes on, they will see your message. :D

**Comment by alphathreethree** [comment]
Ok. So I must be doing something wrong. I don't see any messages when I click the link: https://www.hipchat.com/gUNi66HSC

Is that the correct link?

Edit: nevermind about the username

**Comment by CaliberMengsk** [comment]
O-o after opening it in an incognito and it didn't have the history. So I guess it only shows the history to people that are on the "team", which is limited to 5 people for the free version, so I suppose we should look into something else. If we need, I can set something up on my site (a forum or what not).

**Comment by SuperWes** [comment]
Any ideas? I like Slack, but I think requiring an approved email to begin collaborating isn't in the spirit of the project.

**Comment by alphathreethree** [comment]
I have never used slack but it seems really interesting. I would use it. What about google groups? It looks like it is still around.
