### ISSUE TITLE
Vertically Scrolling Shooter that changes to a twin stick shooter when you land

### ISSUE THREAD

**Issue by SuperWes** [IGDAStl/gateway2dwest#7]
I was thinking it would be interesting to build a game about making your way toward huge monsters, landing on their backs, and fighting off enemies as you make your way toward the monster's core.

Each level begins as a vertically or horizontally scrolling shooter like Ikaruga or a Cave game, but after flying through a relatively short, pre-defined level you arrive at the monster and the game transitions seamlessly to a top down twin stick shooter where you fight waves of enemies and explore the giant monster's back and make your way toward its weak point.

It's somewhat ambitious from a level design perspective, but it's all pretty common stuff for games.

**Comment by kurtosterhage** [comment]
That sounds like a pretty awesome idea. Makes me think of a combination of Shadow of the Colossus and a shmup. Are you thinking more bullet-hell style, like a Cave shooter, or something less intimidating to players, like 1942?

**Comment by SuperWes** [comment]
I'm not sure that needs to be decided just yet, but something that can maintain the feeling/general difficulty level between the different mechanics would be ideal. There could even be a Mega Man style stage selection screen since each level is based on a "boss".

**Comment by CaliberMengsk** [comment]
Sounds ok, though I personal think a dual stick platformer (like hive jump) is more fun then a top down dual stick control. Largely personal opinion though.

**Comment by terrortimmy** [comment]
i like this idea a lot!

**Comment by SuperWes** [comment]
This is an excellent idea, but the group has spoken and we will be making a Spelunky-style random dungeons as a top down action adventure (Gauntlet/Binding of Isaac)
