### ISSUE TITLE
Another suggestion for the project

### ISSUE THREAD

**Issue by alphathreethree** [IGDAStl/gateway2dwest#9]
This idea kind of ballooned on me. It might not be feasible in a short time frame. Let me know what you think. I am not married to the design. I spent a couple hours writing it up; anything could be changed if we wanted to use this.

The gist of it: since the project is named gateway2dwest, the game should be about the frontier to the west. Break the traditional left to right side scroller to a right to left side scroller (i.e. going west :)

https://drive.google.com/file/d/0B9lV4kK0Q9ivSnVuUWI1by1nZkw1aWpWMU9fXzNnelNCUG1v/view?usp=sharing

**Comment by alphathreethree** [comment]
Two options poorly drawn for the type of 2d:

![unnamed](https://cloud.githubusercontent.com/assets/2031558/8886716/df601ba2-3234-11e5-9067-b4c02964a451.png)

**Comment by terrortimmy** [comment]
this is a pretty cool idea!

**Comment by cassdeckard** [comment]
I like it too!

**Comment by SuperWes** [comment]
This is an excellent idea, but the group has spoken and we will be making a Spelunky-style random dungeons as a top down action adventure (Gauntlet/Binding of Isaac)
